directories:
  output: build
  buildResources: build
productName: bufer
appId: com.example.yourapp
files:
  - filter:
      - dist/electron/**/*
publish:
  - provider: generic
    url: 'http://localhost:5080/update'
dmg:
  contents:
    - x: 410
      'y': 150
      type: link
      path: /Applications
    - x: 130
      'y': 150
      type: file
mac:
  icon: build/icons/icon.icns
win:
  icon: build/icons/icon.ico
linux:
  icon: build/icons
electronVersion: 12.0.2
